# Generated by Django 5.2.7 on 2025-10-31 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Riddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riddle_text', models.TextField(unique=True)),
                ('lead_name', models.CharField(blank=True, help_text='Internal note for which lead this is', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_answer', models.CharField(help_text='The exact, all-caps, decrypted string', max_length=255)),
                ('is_complete', models.BooleanField(default=False)),
                ('assigned_riddle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.riddle')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
